### ISSUE TITLE
Переименовать репозиторий

### ISSUE THREAD

**Issue by ak-itacademy** [Melklo/space_invaders#1]
Необходимо переименовать репозиторий.
Во-первых, лучше использовать только строчные буквы, то есть не нужно писать Blueprints, лучше blueprints.
Во-вторых, блупринты - это только часть проекта, поэтому лучше назвать просто space_invaders, а в README.md уже можно указать, что основной фишкой и центральной частью проекта являются блупринты.

**Comment by Melklo** [comment]
Сделано
